GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mzc5NDAwNTV9.ykk-_lFoBJ9SmCHSfaxNLe0DykQStjxp-LdKfDIDN7Q

###

POST http://localhost:3000/login
Content-Type: application/javascript

{
  "username": "Olegas"
}